@XauAi_Api_HostAddress = http://localhost:5081

GET {{XauAi_Api_HostAddress}}/health
Accept: application/json

###

GET {{XauAi_Api_HostAddress}}/api/system/status
Accept: application/json
X-Correlation-ID: local-http-file
